name: goaction

on:
  #schedule:
    #- cron: '0 0 */15 * *' # uncomment this schedule to run at midnight every 15 day of every months
  push:
    paths:
      - '**'
      - '!README.md'
      - '!**/.gitignore'
      - '!**/Dockerfile'
      - '!**/LICENSE'

jobs:
  goaction:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Set up environment variables
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "REPO_FOLDER_1=content/en" >> $GITHUB_ENV
          echo "REPO_FOLDER_2=content/it" >> $GITHUB_ENV
          echo "REPO_URL=https://github.com/cncf/glossary" >> $GITHUB_ENV
      - name: Execute Go Script
        run: go run main.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_FOLDER_1: ${{ env.REPO_FOLDER_1 }}
          REPO_FOLDER_2: ${{ env.REPO_FOLDER_2 }}
          REPO_URL: ${{ env.REPO_URL }}
